pipeline:
  name: build-connector-git
  identifier: buildconnectorgit
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: testinggithub
        repoName: go-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: gitclone
        identifier: gitclone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Welcome to Harnes
                  identifier: Welcome_to_Harnes
                  spec:
                    shell: Sh
                    command: echo "Welcome to "Harness
