pipeline:
  name: build-connector-git
  identifier: buildconnectorgit
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: testinggithub
        repoName: go-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: gitclone
        identifier: gitclone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Welcome to Harnes
                  identifier: Welcome_to_Harnes
                  spec:
                    shell: Sh
                    command: echo "Welcome to "Harness
              - step:
                  type: AquaTrivy
                  name: AquaTrivy_1
                  identifier: AquaTrivy_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      detection: auto
                    advanced:
                      log:
                        level: info
                    privileged: true
                    image:
                      type: docker_v2
                      tag: latest
                      name: wre
                    sbom:
                      format: spdx-json
                  description: Scan complete repo code
